"""Add categories and update models

Revision ID: 3723761e6309
Revises: 723d72f23726
Create Date: 2025-05-28 11:16:24.715995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3723761e6309'
down_revision: Union[str, None] = '723d72f23726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('extended', sa.Boolean(), nullable=False))
    op.drop_index(op.f('idx_loan_book_returned'), table_name='loan')
    op.drop_index(op.f('idx_loan_due_date_returned'), table_name='loan')
    op.drop_index(op.f('idx_loan_user_returned'), table_name='loan')
    op.drop_index(op.f('ix_loan_is_returned'), table_name='loan')
    op.create_index('idx_loan_book_id', 'loan', ['book_id'], unique=False)
    op.create_index('idx_loan_return_date', 'loan', ['return_date'], unique=False)
    op.create_index('idx_loan_user_id', 'loan', ['user_id'], unique=False)
    op.drop_column('loan', 'renewal_count')
    op.drop_column('loan', 'is_returned')
    op.drop_column('loan', 'fine_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('fine_amount', sa.INTEGER(), nullable=False))
    op.add_column('loan', sa.Column('is_returned', sa.BOOLEAN(), nullable=False))
    op.add_column('loan', sa.Column('renewal_count', sa.INTEGER(), nullable=False))
    op.drop_index('idx_loan_user_id', table_name='loan')
    op.drop_index('idx_loan_return_date', table_name='loan')
    op.drop_index('idx_loan_book_id', table_name='loan')
    op.create_index(op.f('ix_loan_is_returned'), 'loan', ['is_returned'], unique=False)
    op.create_index(op.f('idx_loan_user_returned'), 'loan', ['user_id', 'is_returned'], unique=False)
    op.create_index(op.f('idx_loan_due_date_returned'), 'loan', ['due_date', 'is_returned'], unique=False)
    op.create_index(op.f('idx_loan_book_returned'), 'loan', ['book_id', 'is_returned'], unique=False)
    op.drop_column('loan', 'extended')
    # ### end Alembic commands ###
