"""Ajout des modèles avec relations et contraintes

Revision ID: 723d72f23726
Revises: 3e83e09ddef8
Create Date: 2025-05-28 10:48:37.804165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723d72f23726'
down_revision: Union[str, None] = '3e83e09ddef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('book_category',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    op.add_column('book', sa.Column('publisher', sa.String(length=100), nullable=True))
    op.add_column('book', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    op.create_index('idx_book_title_author', 'book', ['title', 'author'], unique=False)
    op.add_column('loan', sa.Column('is_returned', sa.Boolean(), nullable=False))
    op.add_column('loan', sa.Column('renewal_count', sa.Integer(), nullable=False))
    op.add_column('loan', sa.Column('fine_amount', sa.Integer(), nullable=False))
    op.create_index('idx_loan_book_returned', 'loan', ['book_id', 'is_returned'], unique=False)
    op.create_index('idx_loan_due_date_returned', 'loan', ['due_date', 'is_returned'], unique=False)
    op.create_index('idx_loan_user_returned', 'loan', ['user_id', 'is_returned'], unique=False)
    op.create_index(op.f('ix_loan_is_returned'), 'loan', ['is_returned'], unique=False)
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    op.drop_index(op.f('ix_loan_is_returned'), table_name='loan')
    op.drop_index('idx_loan_user_returned', table_name='loan')
    op.drop_index('idx_loan_due_date_returned', table_name='loan')
    op.drop_index('idx_loan_book_returned', table_name='loan')
    op.drop_column('loan', 'fine_amount')
    op.drop_column('loan', 'renewal_count')
    op.drop_column('loan', 'is_returned')
    op.drop_index('idx_book_title_author', table_name='book')
    op.drop_column('book', 'pages')
    op.drop_column('book', 'language')
    op.drop_column('book', 'publisher')
    op.drop_table('book_category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
